AUT-2788: implement logout instead of lockout for sms mfa in reauth
govuk-one-login/authentication-frontend pull request #1829
Opened 2024-07-15 11:21 UTC by LazarAlexandru-Constantin

## What

In the reauth journey, want to redirect the user to the client redirectUri when he enters six invalid otp codes, instead of locking them out for six hours..

## How to review

1. Code Review

## Checklist

- [ ] Performance analyst has been notified of the change.

- [ ] A UCD review has been performed.

- [ ] Any necessary changes to the [acceptance tests](https://github.com/govuk-one-login/authentication-acceptance-tests) have been made.

2024-07-17 07:00 UTC, di-fabs commented on src/components/common/verify-code/verify-code-controller.ts
> +        if (result.data.code === ERROR_CODES.ENTERED_INVALID_MFA_MAX_TIMES) {
Because you don't have any "else" for this "if", that means you can add this condition to your first `if`.
That will simplify your check.

2024-07-17 11:07 UTC, andrew-moores requested changes

2024-07-17 11:07 UTC, andrew-moores commented on src/components/enter-mfa/tests/enter-mfa-integration.test.ts
Add a test for the reauth journey when the reauth feature switch is off.

2024-07-17 11:07 UTC, andrew-moores commented on src/components/enter-mfa/tests/enter-mfa-integration.test.ts
> +          reauthenticate: "12345",
The only journey being tested is a reauth journey, worth testing for non-reauth journey to.

2024-07-31 14:32 UTC, dbes-gds approved these changes

2024-07-31 14:48 UTC, andrew-moores approved these changes

2024-08-01 08:01 UTC, merged