[DFC-661]: Run precommit
govuk-one-login/authentication-frontend pull request #2117
Opened 2024-09-30 15:37 UTC by SophiaDWokoma

## What

Implemented conditional rendering of the beta banner in the base.njk file to ensure it is only visible in web view. Also, added integration tests to verify the functionality.

## How to review

## Checklist

- [ ] Performance analyst has been notified of the change.

- [ ] A UCD review has been performed.

- [ ] Any necessary changes to the [acceptance tests](https://github.com/govuk-one-login/authentication-acceptance-tests) have been made.

- [ ] Documentation has been updated to reflect these changes.

## Related PRs

2024-10-03 14:55 UTC, di-aholme commented
Internal sign off done - works locally as expected. Ready for handover to auth team

2024-10-03 15:10 UTC, Joanneyoung01 commented
Tested and verified locally - LGTM

2024-10-03 15:10 UTC, Joanneyoung01 submitted a review, later dismissed

2024-10-03 17:56 UTC, gtvj requested changes
Hi @SophiaDWokoma 👋🏽 

Thank you for your work on this. I haven't yet reviewed the code or PR, but it seems but it seems some of the comments I've provided on https://github.com/govuk-one-login/authentication-frontend/pull/2114#pullrequestreview-2346268085 might be relevant here too. Would you be OK to look into these?

2024-10-07 08:20 UTC, gtvj commented on src/components/common/layout/base.njk
> +        {% if webChannel %}
See [comment on related PR](https://github.com/govuk-one-login/authentication-frontend/pull/2114/files#r1786608393) about inverting the logic

2024-10-07 08:21 UTC, gtvj commented
Hi @SophiaDWokoma - thanks for your [recent comment](https://github.com/govuk-one-login/authentication-frontend/pull/1109#issuecomment-2393902490) (and apologies that I'd started the thread in the wrong PR, I'd been doing a lot of context switching). I have moved the comment to [the right place](https://github.com/govuk-one-login/authentication-frontend/pull/2114#issuecomment-2396141399) now and provided a bit more context.

We tend to avoid using "squash and merge" because it loses information that might be useful to future developers.

2024-10-15 21:47 UTC, SophiaDWokoma commented
> Hi @SophiaDWokoma - I've made just a couple of suggestions on this PR relating to the way tests are described.
> 
> Like #2114, my sense is that the commits for this PR would benefit from being brought in line with [The GDS Way - Working with Git](https://gds-way.digital.cabinet-office.gov.uk/standards/source-code/working-with-git.html#commits) guidance that I shared previously. There are four commits currently and, given this is a single step (i.e. hiding the phase banner), I'd have thought this would would probably be appropriate to include in a single commit.

Sorry, I don't understand what you mean by this. Do you want all the changes to be in 1 commit ?

2024-10-15 21:57 UTC, SophiaDWokoma commented on src/components/common/layout/tests/base-integration.test.ts
> +  it("beta banner should not be on page", async () => {
Updated

2024-10-15 21:57 UTC, SophiaDWokoma commented on src/components/common/layout/tests/base-integration.test.ts
> +  it("beta banner should be on page", async () => {
Updated

2024-10-17 09:35 UTC, gtvj approved these changes

2024-10-18 12:08 UTC, merged