AUT-3907: Moving Authdev2 to Shared Dev shared VPC
govuk-one-login/authentication-frontend pull request #2426
Opened 2024-12-17 13:17 UTC by pskushwaha1

## What

AUT-3907: Moving Authdev2 to Shared Dev VPC & Also run Authdev2 ECS service under dev cluster 

## How to review

1. Code Review
2. Deploy to Authdev2  with `./deploy-authdev2.sh -t -p

2024-12-18 16:03 UTC, whi-tw requested changes

2025-01-07 11:41 UTC, whi-tw requested changes
There are two commits with identical messages - can these be squashed together?

Other than that, LGTM

2025-01-07 12:26 UTC, pskushwaha1 commented
> There are two commits with identical messages - can these be squashed together?
> 
> Other than that, LGTM

Done

2025-01-07 12:54 UTC, whi-tw approved these changes

2025-01-07 13:01 UTC, merged